export const routes = {
  public: {
    home: "/",
    properties: "/properties",
    propertyDetail: (slug: string) => `/properties/${slug}` as const,
    blog: "/blog",
    blogPost: (slug: string) => `/blog/${slug}` as const,
    blogCategory: (slug: string) => `/blog/kategori/${slug}` as const,
    blogTag: (slug: string) => `/blog/etiket/${slug}` as const,
    contact: "/contact",
    about: "/about",
  },
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin",
    properties: "/admin/properties",
    propertyCreate: "/admin/properties/new",
    propertyDetail: (id: string) => `/admin/properties/${id}` as const,
    propertyEdit: (id: string) => `/admin/properties/${id}/edit` as const,
    propertyPreview: (id: string) => `/admin/properties/${id}/preview` as const,
    blog: "/admin/blog",
    blogCreate: "/admin/blog/new",
    blogDetail: (id: string) => `/admin/blog/${id}` as const,
    blogEdit: (id: string) => `/admin/blog/${id}/edit` as const,
    blogPreview: (id: string) => `/admin/blog/${id}/preview` as const,
    blogCategories: "/admin/blog/categories",
    blogTags: "/admin/blog/tags",
    media: "/admin/media",
    leads: "/admin/leads",
    favorites: "/admin/favorites",
    contact: "/admin/contact",
    users: "/admin/users",
    settings: "/admin/settings",
    logs: "/admin/logs",
  },
  api: {
    auth: "/api/auth",
    health: "/api/health",
  },
} as const;

export type Routes = typeof routes;
